# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/moksh/Documents/Development/TextMateGUI/ui/errorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_errorDialog(object):
    def setupUi(self, errorDialog):
        errorDialog.setObjectName("errorDialog")
        errorDialog.resize(390, 150)
        errorDialog.setMinimumSize(QtCore.QSize(390, 150))
        errorDialog.setMaximumSize(QtCore.QSize(390, 150))
        self.label = QtWidgets.QLabel(errorDialog)
        self.label.setGeometry(QtCore.QRect(70, 30, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(errorDialog)
        QtCore.QMetaObject.connectSlotsByName(errorDialog)

    def retranslateUi(self, errorDialog):
        _translate = QtCore.QCoreApplication.translate
        errorDialog.setWindowTitle(_translate("errorDialog", "Dialog"))
        self.label.setText(_translate("errorDialog", "Please select Image"))
